-- ==========================================
-- 💰 ДОБАВЛЕНИЕ ТАБЛИЦЫ ЗАПРОСОВ НА ПОПОЛНЕНИЕ
-- ==========================================

-- Создаем таблицу если её нет
CREATE TABLE IF NOT EXISTS public.deposit_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id),
    amount_rub FLOAT NOT NULL,                -- Сумма в рублях
    amount_usd FLOAT NOT NULL,                -- Сумма в USD (конвертированная)
    method TEXT NOT NULL,                     -- Способ: 'card' или 'crypto'
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    worker_id BIGINT,                         -- ID воркера (реферера)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    processed_at TIMESTAMP WITH TIME ZONE
);

-- Создаем индексы
CREATE INDEX IF NOT EXISTS idx_deposit_requests_worker ON public.deposit_requests(worker_id, status);
CREATE INDEX IF NOT EXISTS idx_deposit_requests_user ON public.deposit_requests(user_id, status);

-- Включаем RLS
ALTER TABLE public.deposit_requests ENABLE ROW LEVEL SECURITY;

-- Удаляем старую политику если есть
DROP POLICY IF EXISTS "Enable all for deposit_requests" ON public.deposit_requests;

-- Создаем политику
CREATE POLICY "Enable all for deposit_requests" 
ON public.deposit_requests 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- Обновляем publication для realtime
-- Сначала удаляем старую
DROP PUBLICATION IF EXISTS supabase_realtime;

-- Создаем новую с deposit_requests
CREATE PUBLICATION supabase_realtime FOR TABLE public.users, public.trades, public.settings, public.deposit_requests;

-- Проверка
SELECT 'Таблица deposit_requests успешно добавлена! ✅' as status;

SELECT 
    tablename,
    policyname,
    permissive,
    cmd
FROM pg_policies 
WHERE tablename = 'deposit_requests';
