-- ==========================================
-- 🧨 1. ОЧИСТКА (СБРОС СТАРЫХ ТАБЛИЦ)
-- ==========================================
DROP TABLE IF EXISTS public.user_promos;
DROP TABLE IF EXISTS public.promo_codes;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.settings;
DROP PUBLICATION IF EXISTS supabase_realtime;

-- ==========================================
-- 👤 2. ТАБЛИЦА ПОЛЬЗОВАТЕЛЕЙ (МАМОНТЫ)
-- ==========================================
CREATE TABLE public.users (
    user_id BIGINT PRIMARY KEY,              -- Telegram ID (общий для бота и сайта)
    username TEXT,                           -- @username
    full_name TEXT,                          -- Имя
    photo_url TEXT,                          -- Аватарка из Telegram
    referrer_id BIGINT,                      -- ID пригласившего (для воркера)
    
    -- Финансы
    balance FLOAT DEFAULT 0,                 -- Баланс
    
    -- Игровая механика
    luck TEXT DEFAULT 'default' CHECK (luck IN ('win', 'lose', 'default')),
    
    -- Статусы и Доп. поля
    is_kyc BOOLEAN DEFAULT FALSE,            -- Верификация
    web_registered BOOLEAN DEFAULT FALSE,    -- Заходил ли через сайт
    email TEXT DEFAULT '-',                  -- Заглушка для профиля
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Индекс для мгновенного поиска мамонтов у воркера
CREATE INDEX idx_users_referrer ON public.users(referrer_id);

-- ==========================================
-- ⚙️ 3. ТАБЛИЦА НАСТРОЕК (АДМИНКА)
-- ==========================================
CREATE TABLE public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_username TEXT DEFAULT 'etoooroSupport_Official',
    bank_details TEXT DEFAULT 'СБП: Нет данных'
);

-- Инициализация настроек (чтобы не было пусто)
INSERT INTO public.settings (support_username, bank_details)
VALUES ('etoooroSupport_Official', 'СБП (Сбер): Перевод по номеру карты...');

-- ==========================================
-- 📈 4. ТАБЛИЦА СДЕЛОК (TRADES)
-- ==========================================
CREATE TABLE public.trades (
    id TEXT PRIMARY KEY,                      -- UUID сделки
    user_id BIGINT NOT NULL REFERENCES public.users(user_id),
    pair TEXT NOT NULL,                       -- Например "TON/USDT"
    symbol TEXT NOT NULL,                     -- Например "TON"
    type TEXT NOT NULL CHECK (type IN ('Long', 'Short')),
    amount FLOAT NOT NULL,                    -- Сумма ставки
    entry_price FLOAT NOT NULL,               -- Цена входа
    start_time BIGINT NOT NULL,               -- Timestamp начала
    duration_seconds INT NOT NULL,            -- Длительность в секундах
    leverage INT NOT NULL DEFAULT 1,          -- Плечо
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
    final_pnl FLOAT,                          -- Итоговый PnL (после закрытия)
    final_price FLOAT,                        -- Цена закрытия
    is_winning BOOLEAN,                       -- Выиграл или нет
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Индекс для быстрого поиска активных сделок пользователя
CREATE INDEX idx_trades_user_active ON public.trades(user_id, status);

-- ==========================================
-- 💰 5. ТАБЛИЦА ЗАПРОСОВ НА ПОПОЛНЕНИЕ
-- ==========================================
CREATE TABLE public.deposit_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id),
    amount_rub FLOAT NOT NULL,                -- Сумма в рублях
    amount_usd FLOAT NOT NULL,                -- Сумма в USD (конвертированная)
    method TEXT NOT NULL,                     -- Способ: 'card' или 'crypto'
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    worker_id BIGINT,                         -- ID воркера (реферера)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    processed_at TIMESTAMP WITH TIME ZONE
);

-- Индекс для быстрого поиска запросов воркера
CREATE INDEX idx_deposit_requests_worker ON public.deposit_requests(worker_id, status);
CREATE INDEX idx_deposit_requests_user ON public.deposit_requests(user_id, status);

-- ==========================================
-- 🎁 6. ТАБЛИЦЫ ПРОМОКОДОВ
-- ==========================================
CREATE TABLE public.promo_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,            -- Код (например, "START500")
    reward_amount FLOAT NOT NULL,         -- Сумма награды
    max_activations INT DEFAULT 100,      -- Лимит использований
    current_activations INT DEFAULT 0,    -- Сколько раз ввели
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.user_promos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(user_id), -- Кто ввел
    promo_id BIGINT NOT NULL REFERENCES public.promo_codes(id), -- Какой код
    activated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Создаем тестовый промокод "BONUS" на 1000 монет
INSERT INTO public.promo_codes (code, reward_amount, max_activations)
VALUES ('BONUS', 1000, 10000);

-- ==========================================
-- ⚡️ 6. REALTIME (МГНОВЕННОЕ ОБНОВЛЕНИЕ)
-- ==========================================
-- Включаем отслеживание изменений для баланса, сделок, настроек и запросов на пополнение
CREATE PUBLICATION supabase_realtime FOR TABLE public.users, public.trades, public.settings, public.deposit_requests;

-- ==========================================
-- 🔒 7. БЕЗОПАСНОСТЬ (RLS - ПОЛИТИКИ)
-- ==========================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promo_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_promos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deposit_requests ENABLE ROW LEVEL SECURITY;

-- Политики "Разрешить всё всем" (Для корректной работы WebApp и Бота без сложной авторизации)

-- USERS
CREATE POLICY "Enable all for users" ON public.users FOR ALL USING (true) WITH CHECK (true);

-- SETTINGS
CREATE POLICY "Enable all for settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);

-- DEPOSIT REQUESTS
CREATE POLICY "Enable all for deposit_requests" ON public.deposit_requests FOR ALL USING (true) WITH CHECK (true);

-- PROMO CODES
CREATE POLICY "Read Promos" ON public.promo_codes FOR SELECT USING (true);
CREATE POLICY "Update Promos" ON public.promo_codes FOR UPDATE USING (true); -- Чтобы обновлять счетчик
CREATE POLICY "Read User Promos" ON public.user_promos FOR SELECT USING (true);
CREATE POLICY "Insert User Promos" ON public.user_promos FOR INSERT WITH CHECK (true); -- Чтобы записать ввод

-- TRADES
ALTER TABLE public.trades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for trades" ON public.trades FOR ALL USING (true) WITH CHECK (true);

-- ==========================================
-- ✅ ФИНАЛ
-- ==========================================
SELECT 'База данных полностью готова! Поддерживает Бот, Сайт и Промокоды 🚀' as status;